### ISSUE TITLE
Assignments

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-08-18/MEANassignments#1]
Please push your latest assignments

**Comment by dojo-json** [comment]
Any progress?

**Comment by ninos21** [comment]
It's hard right now, I'm in the middle of moving from  California to Massachusetts so there's a lot going on trying sell all our stuff and shipping some...
I'm gonna have to retake MEAN 2, I hate to say it but I have no choice, we've been struggling here I can't find a job and I'm broke so we have to move with my parents in Massachusetts and it's a big move you know.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
